version: '3.8'

services:
  backend:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      MONGODB_USER: root
      MONGODB_PASSWORD: example
      MONGODB_URL: mongo
      MONGODB_DB: tododb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tododb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
